name: Build and Deploy TabCurator

on:
  push:
    branches:
      - main
      - chrome-release
      - firefox-release
      - safari-release
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, firefox, safari]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build for ${{ matrix.browser }}
        run: |
          if [[ "${{ matrix.browser }}" == "chrome" && "${{ github.ref }}" == "refs/heads/chrome-release" ]]; then
            npm run build-chrome;
          elif [[ "${{ matrix.browser }}" == "firefox" && "${{ github.ref }}" == "refs/heads/firefox-release" ]]; then
            npm run build-firefox;
          elif [[ "${{ matrix.browser }}" == "safari" && "${{ github.ref }}" == "refs/heads/safari-release" ]]; then
            npm run build-safari;
          fi

  package:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Package extension for ${{ matrix.browser }}
        run: |
          if [[ "${{ matrix.browser }}" == "chrome" && "${{ github.ref }}" == "refs/heads/chrome-release" ]]; then
            npm run package-chrome;
          elif [[ "${{ matrix.browser }}" == "firefox" && "${{ github.ref }}" == "refs/heads/firefox-release" ]]; then
            npm run package-firefox;
          elif [[ "${{ matrix.browser }}" == "safari" && "${{ github.ref }}" == "refs/heads/safari-release" ]]; then
            npm run package-safari;
          fi

  deploy:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: Deploy to Browser Store
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/chrome-release" ]]; then
            npm run deploy-chrome;
          elif [[ "${{ github.ref }}" == "refs/heads/firefox-release" ]]; then
            npm run deploy-firefox;
          elif [[ "${{ github.ref }}" == "refs/heads/safari-release" ]]; then
            npm run deploy-safari;
          fi